insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('b47553ff-8292-4c20-8531-bd0e5243576e', 'Desayunos', 'El alumno tendrá desayunos nutrivos variados por en smañanas los cuales incluyen frutas y un jugo natural', 298.63, true, 16,'SEMANAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('6b2687c5-9f6e-4e9d-a56b-997fe671799a', 'Transporte', 'El alumno contará con transporte que será capaz de recogerlo en su domicilio y transportarlo hasta la institución', 1478.26, true, 17,'SEMANAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('2447a61e-6855-4884-9a51-a83748bcf864', 'Agua potable', 'El alumno podrá cosumir el agua que la escuela ofrece en los dipensadores repartidor por toda la institución', 1089.14, true, 29,'SEMANAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('5f2119c8-aa75-4dc2-bda5-5746b59667cc', 'Clases de música', 'Taller de música donde el alumno podrá asistir para tomar clases de guitarra, piano, fluata, entre otros intrumentos.', 2655.09, true, 6,'MENSUAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('b15cd5a7-6138-47e6-9387-10eb4437e93b', 'Clases de arte', 'Clases donde el alumno podra desarrollar su creatividad mediante la pintura, las manualidades, entre otras actividades ', 1251.02, false, 3,'MENSUAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('dc0c357f-f08a-414a-b75e-8e8de3547ac2', 'Gimnasia', 'Clases de Gimnasia donde podrá entrar para mejor en ambito artístico a la par de realizar ejercicio', 287.16, true, 5,'ANUAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('95632113-fa06-44d1-be7d-9484ccf6fe64', 'Asesorías matemáticas', 'Asesorias personalizadas donde el alumno podrá resolver sus dudas, encontrar soluciones y mejorar su capacidad de análisis', 1679.6, true, 23,'ANUAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('2c579759-cf64-4990-8941-765063c10181', 'Taller de Ofimática', 'Taller donde el alumno asistirá para desarrollar habilides competitivas para el manejo de la paquetería office de Microsoft', 2309.65, false, 15,'ANUAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('dd376ff2-2b5d-449a-bcf9-880ea33f04b3', 'Atención médica', '
Se brindara atención medica al alumn(a), demanera persistente para detectar cualquier padecimiento que pueda afectar el bienestar saludable, el servicio se paga de manera anual y usted decide 
el horario a tención que este disponible', 2420.5, true, 8,'ANUAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('86b57723-9f81-4bbb-b77d-192690dc86d2', 'Clases de teatro', '
Las clases de teatro es una actividad recreativa para los alumnos donde aprenderan a desarollar diferentes habilidades. El alumn(a) aprendera a comunicarse y expresarse mejor verbalmente, manejo de la voz, movimientos y posturas corporales', 2040.52, true, 10,'ANUAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('218809e2-de68-4a4e-baa9-8369f1d0fbbc', 'Lengua extranjera (Inglés)', '
El alumn(a) desarollara las habilidades necesarias para expresarse correctamente en Inglés, se evaluaria constantemente su comprensón lectora, escucha, habla y redacción. Se imparte durante toda la semana en el area de idiomas', 253.05, false, 8,'MENSUAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('dadbfb8d-9143-4f31-947c-7229f84448e3', 'Lengua extranjera (Francés)', '
El alumn(a) desarollara las habilidades necesarias para expresarse correctamente en Frances, se evaluaria constantemente su comprensón lectora, escucha, habla y redacción. Se imparte durante toda la semana de idiomas', 960.23, true, 22,'SEMESTRAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('6c51c79b-f32a-4fb1-9dd4-abec56d73ed7', 'Uniformes', '
Los uniformes se pueden encargar de manera semestral, las tallas disponibles son chica, mediana y grande', 624.26, false, 10,'SEMESTRAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('a7e2b325-5181-4ab4-ad28-f9fa7f6aee6c', 'Guías escolares', '
Las guias escolares se renueban cada mes, son indispensables para cumplir con la curricula del ciclo escolar', 2778.46, true, 31,'SEMESTRAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('18763168-815f-4c7f-9d48-2f3f723f781b', 'literatura y escritura creativa', '
Es una actividad recreativa donde el alumno desarollara diferentes habilidades de redación y expresión-', 1655.64, false, 6,'MENSUAL');
insert into Servicio (Id, Nombre, Descripcion, Costo, Cancelable, FechaPago, FrecuenciaDePago) values ('6c9b9c9f-f781-4f17-94b1-465219b94563', 'Taller de arte y manualidades', '
Los alumnos desarollará su creatividad para mejorar sus habilidades en manualidades y crear decoraciones espectaculares, es una actividad reatia', 2026.94, false, 21,'MENSUAL');
